### ISSUE TITLE
[Feature] More Native MacOS App Icon

### ISSUE THREAD

**Issue by BenShelton** [BenShelton/library-api#39]
**Packages**

Media

**Describe the solution you'd like**

The app icon is square and too large, it would look nicer if it suited the newer macos icon format (rounded corners and smaller)

This icon can be just for MacOS based on the electron builder config.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by BenShelton** [comment]
@BrodieJones Would you be able to help with this?

**Comment by BrodieJones** [comment]
Sorry it's taken a little while. I've worked on the quality of the icon and changed it to specs of the new MacOS updates. Let me know what you think.

![MacOS Icon](https://user-images.githubusercontent.com/84573271/121228452-adad8300-c884-11eb-9183-3981ab401453.png)

**Comment by BenShelton** [comment]
This looks great! Can you open a PR to replace the existing logo with this?
